### ISSUE TITLE
Validate email field only once

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-backend#396]
### We currently validate the email field twice
@seaerchin pointed out in a previous [PR discussion](https://github.com/isomerpages/isomercms-backend/pull/374#discussion_r827854106) that we currently implement some validations in the ORM layer via Sequelize, and these same fields are being repeated in the router layer.

For example, in the `email` column of the users table:

```
// File: database/models/User.ts

    validate: {
      isEmail: true,
    }
```

This same field is also being validated in the router layer:
```
// File: newroutes/users.ts

validator.isEmail(email)
```

This is duplicative and could cause hard-to-debug bugs if a developer only modifies one validator but not the other. We should validate each input field only once in our codebase at the point of input.

**Comment by seaerchin** [comment]
i'm in favour of doing the validation at the router layer rather than at the db. this is because there might be other methods in the service layer that require that the string be an email, which is more difficult to do if we enforce the validation on the database model. however, it's easy to write a wrapper around our db model to cast the type directly from `string` -> `email`. wdyt?
